### PR TITLE
docs: ghpages

### PR DESCRIPTION
**Pull request by justinchuby**

### CODE REVIEW

**Review by gramalingam — APPROVED** [review]
Will this publish the pages, or is this a preparatory step?

TBH, I don't know enough about this to provide a technical/critical review.

**Comment by gramalingam** [comment]
Well, I see the pages already exist ...

**Comment by justinchuby** [comment]
I think it's because aaron added this branch to trigger deployment too. I am going to remove it

**Comment by justinchuby** [comment]
@abock merging this now

**Pull request merged**
