### PR TITLE
chore(ci): test with onnx weekly build

### PR DESCRIPTION
**Pull request by justinchuby**
Run with builds on https://test.pypi.org/project/onnx-weekly/

### CODE REVIEW

**Comment by justinchuby** [comment]
Strange: I see onnx-weekly installed

```
  _________________ ERROR collecting onnxscript/analysis_test.py _________________
  ImportError while importing test module '/home/runner/work/onnx-script/onnx-script/onnxscript/analysis_test.py'.
  Hint: make sure your test modules/packages have valid Python names.
  Traceback:
  /opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/importlib/__init__.py:126: in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
  onnxscript/__init__.py:6: in <module>
      from .backend.onnx_export import export2python as proto2python
  onnxscript/backend/onnx_export.py:11: in <module>
      from onnx import FunctionProto, ModelProto, TensorProto, ValueInfoProto
  E   ImportError: cannot import name 'FunctionProto' from 'onnx' (unknown location)
```

**Comment by jcwchen** [comment]
It seems onnx package has not been installed... perhaps pip show onnx after installing onnx-weekly to check?

**Comment by justinchuby** [comment]
there's only onnx-weekly but not onnx, which is expected I think?

**Comment by jcwchen** [comment]
> there's only onnx-weekly but not onnx, which is expected I think?

Yes, that should be expected. How about running `python -c "from onnx import FunctionProto"` after installing onnx-weekly?

**Comment by justinchuby** [comment]
```
  test-onnx-weekly: commands[1]> python -c 'from onnx import FunctionProto'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ImportError: cannot import name 'FunctionProto' from 'onnx' (unknown location)
```

**Comment by justinchuby** [comment]
Replaced by #396

**Pull request closed without merging**
