### PR TITLE
chore(lint): use mypy 1.0.0

### PR DESCRIPTION
**Pull request by justinchuby**
"40% faster." https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html

### CODE REVIEW

**Review by jcwchen — APPROVED** [review]
Regarding the pipeline error:
```
Looking in indexes: https://test.pypi.org/simple/
Collecting onnx-weekly
  Downloading https://test-files.pythonhosted.org/packages/9e/43/78e78b495e9c12bb50d5be945eb2ade2f2de47bd82c8662535ee27af733b/onnx-weekly-1.14.0.dev20230206.tar.gz (11.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 42.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://test.pypi.org/simple/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]
```
pip install setuptools>=40.8.0 before installing TestPyPI package should help.

**Comment by justinchuby** [comment]
> Regarding the pipeline error:
> 
> ```
> Looking in indexes: https://test.pypi.org/simple/
> Collecting onnx-weekly
>   Downloading https://test-files.pythonhosted.org/packages/9e/43/78e78b495e9c12bb50d5be945eb2ade2f2de47bd82c8662535ee27af733b/onnx-weekly-1.14.0.dev20230206.tar.gz (11.2 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 42.9 MB/s eta 0:00:00
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'error'
>   error: subprocess-exited-with-error
>   
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [3 lines of output]
>       Looking in indexes: https://test.pypi.org/simple/
>       ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
>       ERROR: No matching distribution found for setuptools>=40.8.0
>       [end of output]
> ```
> 
> pip install setuptools>=40.8.0 before installing TestPyPI package should help.

It's failing because the latest weekly does not have a linux wheel. Was it able to rerun? Normally we don't need these depencencies.

**Comment by jcwchen** [comment]
> It's failing because the latest weekly does not have a linux wheel. Was it able to rerun? Normally we don't need these dependencies.

I see. ONNX pipelines are green now, I will rerun it soon.

**Comment by jcwchen** [comment]
> It's failing because the latest weekly does not have a linux wheel. Was it able to rerun? Normally we don't need these dependencies.

That pipeline is still using the codebase with wrong URLs so it cannot rerun successfully... It has been fixed in the main branch so next weekly package should be good

**Pull request merged**
