### PR TITLE
Create github actions for faster CI

### LINKED ISSUE #141: Run CI with Github actions
The queue time on ADO is longer than the actual execution time. Too much wait.

### PR DESCRIPTION
**Pull request by justinchuby**
Fixes #141 #142 

- Replicate tests run in ADO to github actions
- Use pytest-xdist to enable parallel testing
- Install `wheel` in the test environments

### CODE REVIEW

**Comment by abock** [comment]
Note that we should still keep the ADO pipelines.

**Comment by justinchuby** [comment]
@abock curious why?

**Comment by justinchuby** [comment]
@AllenTiTaiWang  py3.7 ADO test flaky because of isort[colors] `WARNING: isort does not provide the extra 'colors'`

**Comment by AllenTiTaiWang** [comment]
> @AllenTiTaiWang py3.7 ADO test flaky because of isort[colors] `WARNING: isort does not provide the extra 'colors'` I removed colors

Thanks, I got that from
https://github.com/onnx/onnx/blob/de2459972d3f834dba24a586982d1ffce5532e0b/setup.py#L343-L350

Not sure if we need to address this one too?

**Comment by justinchuby** [comment]
Maybe. I just added colorama manually

**Comment by justinchuby** [comment]
I think I fixed the python 3.7 test.

**Pull request merged**
