### PR TITLE
Upgrade lint dependencies | chore(lint)

### PR DESCRIPTION
**Pull request by justinchuby**
Upgrade all lint dependencies and fix new lint errors

### CODE REVIEW

**Comment by justinchuby** [comment]
@jcwchen I wonder if we should have a requirements-lint file and let dependabot take over. What do you think?

**Review by jcwchen — APPROVED** [review]
>@jcwchen I wonder if we should have a requirements-lint file and let dependabot take over. What do you think?

I am exactly thinking the same thing! but would it be one PR or multiple PRs if there are few dependency updates in a period? If it would be just one PR, it seems like a good idea.

**Comment by jcwchen** [comment]
> I am exactly thinking the same thing! but would it be one PR or multiple PRs if there are few dependency updates in a period? If it would be just one PR, it seems like a good idea.

After consideration, ideally these dependencies should not update too often at the same time? Then I am fine with using dependabot anyway.

**Comment by justinchuby** [comment]
I will need to update the lintrunner adapters package to support using a requirements.txt file. I will actually move that script to here

**Comment by justinchuby** [comment]
I think we can configure the frequency

**Comment by justinchuby** [comment]
Merged. Figures crossed dependabot works

**Pull request merged**
