### PR TITLE
Fix conversion between onnxscript and ort representation

### PR DESCRIPTION
**Pull request by gramalingam**
Handle conversion of lists between onnxscript and ort.

Fixes https://github.com/microsoft/onnx-script/issues/351

### CODE REVIEW

**Review by justinchuby — APPROVED** [review]
This is awesome, thanks! 🙌

**Comment by justinchuby** [comment]
FAILED onnxscript/test/function_libs/torch_aten/ops_correctness_test.py::TestOutputConsistencyCPU::test_output_match_cat_cpu_float32

Unexpected success (which proves this fix works!)

May need to remove an xfail(“cat”) in the test file

**Comment by gramalingam** [comment]
There seem to be some flakiness with the CIs, again relating to tox.

**Comment by gramalingam** [comment]
Why does my local lintrunner not catch this blank space/line that CI lint is complaining about?

**Comment by gramalingam** [comment]
Better still, why doesn't `linrtunner format` do it?

**Comment by justinchuby** [comment]
> There seem to be some flakiness with the CIs, again relating to tox.

I think that’s an actual failure. You may expand the error message to see it

**Comment by justinchuby** [comment]
Try lintrunner f —all-files or lintrunner f -m main? Lintrunner by default only operates on the file diff against HEAD

**Comment by gramalingam** [comment]
well, lintrunner init seemed to have helped. Not sure when exactly that is required.

**Comment by justinchuby** [comment]
there were still errors - pushing a forward fix

**Pull request merged**
