### PR TITLE
docs: update lintrunner instructions

### PR DESCRIPTION
**Pull request by justinchuby**

### CODE REVIEW

**Review by titaiwangms — APPROVED** [review]
`lintrunner f -m main` works great with all passed format checks, but `lintrunner f` and `lintrunner -a` doesn't work with this repo. Do you have any idea thes reason behind this?

**Comment by justinchuby** [comment]
> `lintrunner f -m main` works great with all passed format checks, but `lintrunner f` and `lintrunner -a` doesn't work with this repo. Do you have any idea thes reason behind this?

Can you explain what doesn’t work? I expect them to “work” but we need -m main to find all the modified files. So lintrunner f -m main and lintrunner -a -m main. Since mypy is slow and ppl running -a usually just want to format the code I changed -a to f

**Comment by titaiwangms** [comment]
> > `lintrunner f -m main` works great with all passed format checks, but `lintrunner f` and `lintrunner -a` doesn't work with this repo. Do you have any idea thes reason behind this?
> 
> Can you explain what doesn’t work? I expect them to “work” but we need -m main to find all the modified files. So lintrunner f -m main and lintrunner -a -m main. Since mypy is slow and ppl running -a usually just want to format the code I changed -a to f

(pytorch-dev) titaiwang@titaiwanglinuxcpudev:~/onnx-script$ lintrunner f -m main


>>> General linter failure:

  Error (RUFF-FIX) Linter failed
    Linter failed. This a bug, please file an issue against the linter
    maintainer.
    
    CONTEXT:
    Linter command failed with non-zero exit code.
    STDERR:
    Usage: python -m lintrunner_adapters run [OPTIONS] {clangformat_linter|
    cmake_l
                                             inter|newlines_linter|pip_init|
    isort_
                                             linter|
    editorconfig_checker_linter|bl
                                             ack_linter|mypy_linter|
    grep_linter|sh
                                             ellcheck_linter|ufmt_linter|
    flake8_li
                                             nter|black_isort_linter|
    exec_linter|p
                                             ylint_linter}
    Try 'python -m lintrunner_adapters run --help' for help.
    
    Error: Invalid value for '{clangformat_linter|cmake_linter|
    newlines_linter|pip_init|isort_linter|editorconfig_checker_linter|
    black_linter|mypy_linter|grep_linter|shellcheck_linter|ufmt_linter|
    flake8_linter|black_isort_linter|exec_linter|pylint_linter}':
    'ruff_fix_linter' is not one of 'clangformat_linter',
    'cmake_linter', 'newlines_linter', 'pip_init', 'isort_linter',
    'editorconfig_checker_linter', 'black_linter', 'mypy_linter',
    'grep_linter', 'shellcheck_linter', 'ufmt_linter', 'flake8_linter',
    'black_isort_linter', 'exec_linter', 'pylint_linter'.
    
    
    STDOUT:
    
Successfully applied all patches.

**Comment by titaiwangms** [comment]
Is it actually something this PR trying to fix?

**Comment by justinchuby** [comment]
> Is it actually something this PR trying to fix?

Not really. we are should probably provide a better experience on this front but for now you may update lintrunner-adapters to get the new adapters for ruff.

**Pull request merged**
